# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11iiBq_EZYG9xHbel3DSNRcYMlCobYCUp
"""

#Ejercicio Calificado #1:
# Obtener Input del Usuario
frase = input("Por favor, introduce una frase: ")
letra = input("Ahora, introduce una letra: ")

fraseMin = frase.lower()
letraMin = letra.lower()

# Contar el número de veces que aparece la letra en la frase
listaFrase = list(fraseMin)
contador = 0
for caracter in listaFrase:
    if caracter == letraMin:
        contador += 1

# Mostrar el resultado
print(f"La letra '{letra}' aparece {contador} veces en la frase: '{frase}'")
